"""Phase B + C: the self-healing Brock loop — search {lead level, battle genome} for the
fewest-turns win.

Each ``(pre-Brock state, genome)`` config is deterministic (PyBoy replays the same RNG, and the
battle strategy is pure), so this is a search over *distinct* configs with k=1 each — not the
wasted k>1 replication of failed experiment 2. The gradient is real here because Brock's Onix is
a wall: move quality (battle genome) and lead level decide both turn count and win/loss.

Self-healing: per generation the loop inspects the best verdict and routes the nudge —
  - didn't reach Brock at all -> nudge nav params (only relevant for full speedrun states),
  - reached but lost          -> escalate the lead level (next state up the ladder),
  - won but slow              -> keep mutating battle params to cut turns.

The loop consumes a *ladder* of pre-Brock save states (``states_dir``). With a single captured
state it optimizes the battle genome at the organic matchup; with level-variants generated by
``python -m autotune.party`` it also climbs the level lever. See ``docs/brock-loop.md`` for how
to capture states for each lever.
"""

from __future__ import annotations

import json
import random
import re
from dataclasses import dataclass
from pathlib import Path

from autotune.brock import BrockVerdict, verify_brock
from autotune.config import Config
from autotune.genome import base_genome
from autotune.rollout import run_batch
from autotune.scenario import BATTLE_PARAM_KEYS, mutate_battle_params, mutate_nav_params
from autotune.selection import is_verdict_better
from autotune.story import build_story, load_routes

_STATE_LEVEL_RE = re.compile(r"l(?:ead_)?lv(\d+)", re.IGNORECASE)


@dataclass(frozen=True)
class Matchup:
    """A rung on the level ladder: a level (None = organic/un-poked) and its save state."""

    level: int | None
    state_path: str


def discover_states(states_dir: Path, fallback_state: str | None = None) -> list[Matchup]:
    """Find pre-Brock states. ``*lv<N>.state`` files form a level ladder (sorted ascending);
    otherwise the single ``fallback_state`` (the organic battle-start capture) is used."""
    states_dir = Path(states_dir)
    ladder: list[Matchup] = []
    if states_dir.is_dir():
        for path in sorted(states_dir.glob("*.state")):
            m = _STATE_LEVEL_RE.search(path.name)
            level = int(m.group(1)) if m else None
            ladder.append(Matchup(level=level, state_path=str(path.resolve())))
    leveled = [m for m in ladder if m.level is not None]
    if leveled:
        return sorted(leveled, key=lambda m: m.level)
    if ladder:
        return ladder
    if fallback_state and Path(fallback_state).exists():
        return [Matchup(level=None, state_path=str(Path(fallback_state).resolve()))]
    return []


def _battle_params(genome: dict) -> dict:
    return {k: round(float(genome[k]), 3) for k in BATTLE_PARAM_KEYS}


def _entry(verdict: BrockVerdict, genome: dict, matchup: Matchup, rollout_dir: str) -> dict:
    return {
        "matchup": {"level": matchup.level, "state_path": matchup.state_path},
        "genome": _battle_params(genome),
        "reward": round(verdict.story_reward, 4),
        "reached_pewter": verdict.reached_pewter,
        "won": verdict.won,
        "turns": verdict.turns,
        "damage_frac": round(verdict.damage_frac, 4),
        "whiteout": verdict.whiteout,
        "lead_species": verdict.lead_species,
        "lead_level": verdict.lead_level,
        "rollout_dir": rollout_dir,
    }


def _evaluate(
    cfg: Config, story, genome: dict, matchup: Matchup, label: str, max_turns: int
) -> tuple[BrockVerdict, str]:
    """One deterministic rollout of ``genome`` at ``matchup``; returns its Brock verdict."""
    work_root = cfg.storage.out_dir / "brock" / label
    rollouts = run_batch(
        cfg,
        params_list=[dict(genome)],
        max_turns=max_turns,
        work_root=work_root,
        concurrency=1,
        load_state=matchup.state_path,
        battle_limit=1,
    )
    r = rollouts[0]
    return verify_brock(story, r.fitness, r.events), str(r.rollout_dir)


def run_brock_loop(
    cfg: Config,
    states_dir: str = "./states/brock",
    fallback_state: str = "./states/pre_brock.state",
    generations: int = 4,
    population: int = 4,
    target_turns: int = 12,
    max_turns: int = 300,
    seed: int = 42,
) -> dict:
    """Search battle genome × level ladder for the fewest-turns Brock win. Returns a summary."""
    ladder = discover_states(Path(states_dir), fallback_state)
    if not ladder:
        raise RuntimeError(
            f"No pre-Brock states found in {states_dir} or at {fallback_state}. "
            "Run the speedrun (python -m autotune.speedrun) first."
        )

    story = build_story("brock", target_map_id=2, routes=load_routes(cfg.env.routes_json))
    rng = random.Random(seed)
    genome = base_genome()
    matchup_idx = 0
    entries: list[dict] = []

    matchup = ladder[matchup_idx]
    best, rdir = _evaluate(cfg, story, genome, matchup, "seed", max_turns)
    best_genome = dict(genome)
    best_matchup = matchup
    entries.append(_entry(best, genome, matchup, rdir))
    print(
        f"[brock] seed: lvl={matchup.level} reward={best.story_reward:.2f} "
        f"won={best.won} turns={best.turns}"
    )

    for gen in range(generations):
        matchup = ladder[matchup_idx]
        scored: list[tuple[BrockVerdict, dict, str]] = []
        for ci, cand in enumerate(mutate_battle_params(genome, rng, population)):
            v, rdir = _evaluate(cfg, story, cand, matchup, f"gen{gen}-c{ci}", max_turns)
            scored.append((v, cand, rdir))
            entries.append(_entry(v, cand, matchup, rdir))

        gen_best, gen_genome, _ = max(
            scored, key=lambda t: (t[0].story_reward, t[0].score)
        )
        if is_verdict_better(gen_best, best):
            best, genome = gen_best, gen_genome
            best_genome, best_matchup = dict(gen_genome), matchup

        print(
            f"[brock] gen {gen}: lvl={matchup.level} best_reward={best.story_reward:.2f} "
            f"won={best.won} turns={best.turns} "
            f"candidates={[round(v.story_reward, 2) for v, _, _ in scored]}"
        )

        # Stop early on a fast win.
        if best.won and best.turns is not None and best.turns <= target_turns:
            print(f"[brock] fast win reached ({best.turns} turns <= {target_turns}). Stopping.")
            break

        # Self-healing routing for the NEXT generation.
        if not best.reached_pewter:
            genome = _heal_nav(genome, rng)  # nudge nav (full-speedrun states only)
        elif not best.won and matchup_idx < len(ladder) - 1:
            matchup_idx += 1  # escalate the lead level
            print(f"[brock] lost — escalating to level {ladder[matchup_idx].level}")
        # else: keep mutating battle params (next generation continues at this matchup).

    _write_outputs(cfg, entries, best, best_genome, best_matchup, target_turns)
    return {
        "best_reward": best.story_reward,
        "brock_won": best.won,
        "brock_turns": best.turns,
        "best_level": best_matchup.level,
        "evaluations": len(entries),
    }


def _heal_nav(genome: dict, rng: random.Random) -> dict:
    return mutate_nav_params(genome, rng, 1)[0]


def _write_outputs(cfg, entries, best, best_genome, best_matchup, target_turns) -> None:
    out_dir = cfg.storage.out_dir / "brock"
    out_dir.mkdir(parents=True, exist_ok=True)
    ranked = sorted(entries, key=lambda e: e["reward"], reverse=True)
    leaderboard = {
        "task": "brock_speedrun",
        "target_turns": target_turns,
        "best": ranked[0] if ranked else None,
        "entries": ranked,
    }
    (out_dir / "leaderboard.json").write_text(json.dumps(leaderboard, indent=2) + "\n")

    best_payload = {
        "genome": best_genome,
        "matchup": {"level": best_matchup.level, "state_path": best_matchup.state_path},
        "reward": best.story_reward,
        "brock_won": best.won,
        "brock_turns": best.turns,
        "damage_frac": best.damage_frac,
        "lead_species": best.lead_species,
        "lead_level": best.lead_level,
    }
    (cfg.storage.out_dir / "best_brock.json").write_text(json.dumps(best_payload, indent=2) + "\n")
    print(f"[brock] leaderboard -> {out_dir / 'leaderboard.json'}")
    print(f"[brock] best config -> {cfg.storage.out_dir / 'best_brock.json'}")
